package GUI;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import json.JsonToJava;
import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.swing.AutoCompleteSupport;

import com.google.gson.JsonSyntaxException;

import de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author apple
 */
public class FirstWindow extends javax.swing.JFrame {

	/**
	 * Creates new form FirstWindow
	 */
	public FirstWindow() {
		initComponents();
		SwingUtilities.invokeLater(doWorkRunnable);
		setSizeAndLocation();
	}

	public void setSizeAndLocation() {
		setSize(700, 433);

		GUIFunctions.setWindowHeight(this.getHeight());
		GUIFunctions.setWindowWidth(this.getWidth());

		// GUIFunctions.setPosX(this.getX());
		// GUIFunctions.setPosX(this.getY());

		GUIFunctions.addResizeEvent(this);

	}

	public void setSizeAndLocationFromPrev() {
		this.setSize(GUIFunctions.getWindowWidth(),
				GUIFunctions.getWindowHeight());
		// this.setLocation(GUIFunctions.getPosX(), GUIFunctions.getPosY());
	}

	Runnable doWorkRunnable = new Runnable() {
		@Override
		public void run() {
			GUIFunctions.start();
			Object elements[];
			try {
				elements = JsonToJava.readCategories();
			} catch (JsonSyntaxException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				elements = new Object[] {};
			}
			// jComboBox1.setModel(new JComboBox<>(elements).getModel());
			AutoCompleteSupport.install(jComboBox1,
					GlazedLists.eventListOf(elements));
			jComboBox1.revalidate();
			jComboBox1.repaint();
		}
	};

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jMenu3 = new javax.swing.JMenu();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jTextFieldLat = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextFieldLong = new javax.swing.JTextField();
		jButtonMap = new javax.swing.JButton();
		jButtonOk = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItemRestart = new javax.swing.JMenuItem();
		jButtonReviews = new javax.swing.JButton();

		jMenu3.setText("jMenu3");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jLabel1.setText("Choose a category");

		jComboBox1.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		// jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]
		// { "Item 1", "Item 2", "Item 3", "Item 4" }));
		Object[] elements = new Object[] {};
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});
		
//		jComboBox1.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);

//		jTextFieldLat.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
//		jTextFieldLat.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jTextFieldLatActionPerformed(evt);
//			}
//		});
//
//		jLabel2.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
//		jLabel2.setText("Latitude");
//
//		jLabel3.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
//		jLabel3.setText("Longitude");
//
//		jTextFieldLong.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
//		jTextFieldLong.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jTextFieldLongActionPerformed(evt);
//			}
//		});
//
//		jButtonMap.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
//		jButtonMap.setText("Select from map");
//		jButtonMap.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jButtonMapActionPerformed(evt);
//			}
//		});

		jButtonOk.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jButtonOk.setText("Topics");
		jButtonOk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonOkActionPerformed(evt);
			}
		});

		jButtonReviews.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
		jButtonReviews.setText("Reviews");
		jButtonReviews.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonReviewsActionPerformed(evt);
			}
		});

		jMenu1.setText("File");

		jMenuItemRestart.setText("Reset");
		jMenuItemRestart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemRestartActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItemRestart);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);
		

		  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jLabel1)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addGap(73, 73, 73)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jButtonOk)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
	                        .addComponent(jButtonReviews)))
	                .addGap(54, 54, 54))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(39, 39, 39)
	                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGap(41, 41, 41)
	                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(62, 62, 62)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButtonReviews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addComponent(jButtonOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                .addContainerGap(51, Short.MAX_VALUE))
	        );

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void jTextFieldLatActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonMapActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.showMap();
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.showWords();
	}

	private void jTextFieldLongActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItemRestartActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.resetFirstWindow();
	}

	private void jButtonReviewsActionPerformed(java.awt.event.ActionEvent evt) {
		GUIFunctions.showReviewsFromFirstWindow();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */

		// try {
		// for (javax.swing.UIManager.LookAndFeelInfo info :
		// javax.swing.UIManager
		// .getInstalledLookAndFeels()) {
		// if ("Nimbus".equals(info.getName())) {
		// javax.swing.UIManager.setLookAndFeel(info.getClassName());
		// break;
		// }
		// }
		// } catch (ClassNotFoundException ex) {
		// java.util.logging.Logger.getLogger(FirstWindow.class.getName())
		// .log(java.util.logging.Level.SEVERE, null, ex);
		// } catch (InstantiationException ex) {
		// java.util.logging.Logger.getLogger(FirstWindow.class.getName())
		// .log(java.util.logging.Level.SEVERE, null, ex);
		// } catch (IllegalAccessException ex) {
		// java.util.logging.Logger.getLogger(FirstWindow.class.getName())
		// .log(java.util.logging.Level.SEVERE, null, ex);
		// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
		// java.util.logging.Logger.getLogger(FirstWindow.class.getName())
		// .log(java.util.logging.Level.SEVERE, null, ex);
		// }
		// </editor-fold>

		try {
//			UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
//			UIManager.setLookAndFeel(new SyntheticaBlueLightLookAndFeel());
			UIManager.setLookAndFeel(new SyntheticaAluOxideLookAndFeel());
		} catch (Exception e) {
			e.printStackTrace();
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
//				WebLookAndFeel.install ();

				FirstWindow fw = new FirstWindow();
				GUIFunctions.firstWindowFrame = fw;
				fw.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButtonMap;
	private javax.swing.JButton jButtonOk;
	private javax.swing.JButton jButtonReviews;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JTextField jTextFieldLat;
	private javax.swing.JTextField jTextFieldLong;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItemRestart;

	// End of variables declaration
	public javax.swing.JTextField getjTextFieldLat() {
		return jTextFieldLat;
	}

	public void setjTextFieldLat(javax.swing.JTextField jTextFieldLat) {
		this.jTextFieldLat = jTextFieldLat;
	}

	public javax.swing.JTextField getjTextFieldLong() {
		return jTextFieldLong;
	}

	public void setjTextFieldLong(javax.swing.JTextField jTextFieldLong) {
		this.jTextFieldLong = jTextFieldLong;
	}

	public javax.swing.JComboBox getjComboBox1() {
		return jComboBox1;
	}

	public void setjComboBox1(javax.swing.JComboBox jComboBox1) {
		this.jComboBox1 = jComboBox1;
	}
}
